Repository opensearch-project/logstash-output-opensearch, pull requests merged in 2021-07, with the labels that each got.

#31 Support TLS Certificate
  lib/logstash/outputs/opensearch/http_client_builder.rb
  lib/logstash/plugin_mixins/opensearch/api_configs.rb
  spec/unit/outputs/opensearch_ssl_spec.rb
Labels: Enhancements

#36 Update error message
  lib/logstash/outputs/opensearch/distribution_checker.rb
  spec/unit/outputs/opensearch/http_client/pool_spec.rb
Labels: v1.0.0, v1.1.0

#39 Update README with badge url
  README.md
Labels: Documentation

#41 Add new docker Multi-Arch image building scripts for logstash-output-opensearch
  dockerfiles/docker-compose.yml
  dockerfiles/run.sh
  release/docker/.gitignore
  release/docker/Dockerfile
  release/docker/build-docker-multi-arch.sh
  release/docker/build-plugin.sh
  release/docker/logstash-opensearch-sample.conf
Labels: Enhancements
