Repository opensearch-project/logstash-output-opensearch, pull requests merged in 2021-12, with the labels that each got.

#105 Adding release-notes 1.2
  release-notes/logstash-output-opensearch.release-notes-1.2.0.md
Labels: 1.2.0

#101 Adding Signing key path to gemspec
  .gitignore
  logstash-output-opensearch.gemspec
Labels: Infrastructure, 1.2.0

#109 Update upstream version to latest release
  .github/workflows/CI.yml
Labels: 1.2.0

#112 Add build script
  .gitignore
  build.sh
Labels: 1.2.0

#116 Add Backport workflow
  .github/workflows/backport.yml
  DEVELOPER_GUIDE.md
Labels: Infrastructure
